# Generated by Django 4.1 on 2023-04-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_critic",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
