# Generated by Django 4.1 on 2023-04-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_is_critic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_critic",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
